training:
  name: oscVis
  description: reid with infoNCE only Fixed testing
  experiment_id: t1
  extra_notes: none
  logs_dir: ../logs/training/reidFinal
  is_train: true
  device: cuda:0
  batch_size: 72
  num_workers: 16
  test_size: 0.1
  n_epochs: 25
  append_loss_every: 250
  print_every: 250
  validate_every: 10090
  save_every: 10090
  #validate_every: 51935
  #save_every: 25000
  save_every_nepochs: 1
  start_epoch: 0
  start_iteration: 0
  visualize_every: 1000
  apply_metrics_every: 500
  #apply_metrics_every: 51935
  use_scheduler: True
  enable_wandb: True
  apply_metrics_batch_count: 64 # number of batches to apply additional metrics on
  load_ckpt: False
  ckpt_path: \"../logs/training/reid/snReidSoccernet/t2/2025_03_26_15_53_40/checkpoints/epoch-best.ckpt\"
dataset:
  dataset_field: player_classif
  path: None
  overfit_size: 5
  split: train # train | valid | test
  is_overfit: False

  sim_matches:
    class_filepath: ./datasets/SimMatches.py 
    class: SimMatches
    path: ./raw_dataset/match_pairs/eval/100k/text
  
  team_clustering:
    class_filepath: ./datasets/TeamClusterDataset.py
    class: TeamClusterDataset
    path: ./raw_dataset/teams_clustering

  visual_sim_matches:
    class_filepath: ./datasets/VisualSimMatches.py 
    class: VisualSimMatches
    #path: ./raw_dataset/match_pairs/eval/200k/visual
   # path: ./raw_dataset/frame_pairs_full_clipped_150_30
    #path: ./raw_dataset/frame_pairs_full_clipped_150_30_fixed
    path: ./raw_dataset/frame_pairs_far
  
  player_classif:
    class_filepath: ./datasets/SoccerNetReid.py
    class: SoccerNetReidDataset
    path: ./raw_dataset/soccernet-reid/raw/reid
    split: "train"
  


model:
  model_field: siamese
  
  dummy_classifier:
    model_filepath: ./pytorchmodels/DummyClassifier.py
    model_class: DummyClassifier
    lr: 0.01
    losses: acc
    weight_init: None 
    criterion: CE
    scheduler_step_size: 5
    scheduler_gamma: 0.5
    dummy_network:
      kernel_size: 3
      padding: 1
  

  jerseyId:
    model_filepath: ./pytorchmodels/jerseyId/jerseyId.py
    model_class: JerseyID
    lr: 0.001
    losses: acc,lc_count,dg1,dg2,cls,tp,predc
    weight_init: None
    criterion: CE
    metrics: None
    scheduler_step_size: 5
    scheduler_gamma: 0.5
    dummy_network:
      kernel_size: 3
      padding: 1

  clip:
    model_filepath: ./clipreid/clip.py
    model_class: Clip
    lr: 0.00004
    #losses: cosp,cosn,nce,cont
    losses: cosp,cosn,nce
    weight_init: None
    criterion: CE
    metrics: None
    name: ViT-B/16
    pretrained: openai
    scheduler_step_size: 5
    scheduler_gamma: 0.5
    dummy_network:
      kernel_size: 3
      padding: 1

  siamese:
    model_filepath: ./pytorchmodels/siameseOSC.py
    model_class: SiameseOSC
    metrics: None
    lr: 0.00004
    losses: acc,cosp,cosn
    weight_init: None
    scheduler_step_size: 5
    scheduler_gamma: 0.5
    use_visual: True
    use_combined: False
    use_bb: False
    use_pnet: False
    use_kp: False
    name: ViT-B/16
    pretrained: openai



  team_classif:
    model_filepath: ./pytorchmodels/TeamClassifier.py
    model_class: TeamClassifier
    lr: 1.0e-3
    losses: acc
    weight_init: None 
    criterion: CE
    scheduler_step_size: 15
    scheduler_gamma: 0.5
    metrics: None

  
  player_classif:
    model_filepath: ./pytorchmodels/PlayerClassification.py
    model_class: PlayerClassification
    lr: 1.0e-3
    losses: acc
    weight_init: None 
    criterion: CE
    scheduler_step_size: 15
    scheduler_gamma: 0.5
    metrics: None

  
  tripletSiamese:
    model_filepath: ./pytorchmodels/SiameseTriplet.py
    model_class: TripletSiamese
    metrics: None
    lr: 1.0e-3
    losses: cosp,cosn
    weight_init: None
    scheduler_step_size: 5
    scheduler_gamma: 0.5
    use_visual: True
    use_combined: False
    use_bb: False
    use_pnet: False
    use_kp: False
    tripletMargin: 0.5


  



